package com.example.citypass.utils;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.citypass.utils.Zan;

import com.example.citypass.utils.ZanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig zanDaoConfig;

    private final ZanDao zanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        zanDaoConfig = daoConfigMap.get(ZanDao.class).clone();
        zanDaoConfig.initIdentityScope(type);

        zanDao = new ZanDao(zanDaoConfig, this);

        registerDao(Zan.class, zanDao);
    }
    
    public void clear() {
        zanDaoConfig.clearIdentityScope();
    }

    public ZanDao getZanDao() {
        return zanDao;
    }

}
